[package]
name = "nemu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.2.1"
ctrlc = "3.4.5"
env_logger = "0.11.6"
log = "0.4.25"
toml = "0.5.9"
